### ISSUE TITLE
Google Capture Not Working

### ISSUE THREAD

**Issue by suFDHAI78fyw78q09Y98yfd** [roytam1/palemoon27#1]
Could not connect to the reCAPTCHA service.

Please check your internet connection and reload to get a reCAPTCHA challenge.

The above means no captcha available at all. Please fix so it does work and check each on update. Seems everyone is using Google (crap) capture now so seems it is needed more :(

New Moon  27.9.1a1 (32-bit) (2018-08-17)
XPSP3 (P3 SSE)

**Comment by roytam1** [comment]
try updating it with latest build (palemoon-27.9.6.win32-git-20190302-d0444154b-xpmod-sse.7z) first.

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
Thanks I found the issue. When unpacked it did so in a sub folder so wasn't the new version I ran. No need to change the way it is need now to installer since we can see and check also AV etc what it is before unpacking and using.

Tested this version many times, and passes the Google rubbish without issue.

Thanks.

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
Thanks again.
